//! Parses the Anchor program's source as *data* and checks it against the spec.
//!
//! # Why this exists
//!
//! The program under `../anchor/` cannot be compiled here: no `solana` CLI, no
//! `anchor` CLI, no `cargo build-sbf`. So the account layout, the PDA seeds and
//! the reject list could drift away from this crate's tables with nothing to
//! notice. This test closes that gap the only way available without a toolchain
//! -- it reads the source with `include_str!` and parses it with `syn`.
//!
//! Both halves of that are established patterns in this repository:
//! `core/crates/ares-core/src/lib.rs` `include_str!`s a generated catalog from
//! across the tree and cross-checks it in a test, and
//! `core/crates/ares-cli/src/poc.rs:707-722` `syn`-parses generated code to prove
//! a property of Rust it deliberately cannot compile.
//!
//! # What this can and cannot prove
//!
//! It proves the constraints are **declared**: that `init` is present, that the
//! authority is a `Signer`, that `bump` takes no argument, that each `require!`
//! exists, that `init_if_needed` does not.
//!
//! It cannot prove any of them is **enforced**. A `syn` parse sees tokens, not
//! macro expansion or runtime behaviour. "The program rejects an overwrite" is
//! not provable until `anchor test` runs against a localnet. That distinction is
//! the honest boundary of the whole on-chain half, and it belongs in the PR
//! description as much as here.

use quote::ToTokens;

/// The program source, embedded at compile time so a rename or a move breaks the
/// build rather than silently skipping every assertion below.
const PROGRAM_SRC: &str = include_str!("../../anchor/programs/evidence_registry/src/lib.rs");

/// The placeholder program id. An operator replaces this once they generate the
/// program keypair -- which is a private key, so it is generated by a human and
/// never by CI or by an agent.
const PLACEHOLDER_PROGRAM_ID: &str = "Evid1111111111111111111111111111111111111111";

fn parsed() -> syn::File {
    syn::parse_file(PROGRAM_SRC).expect("the program source is not parseable Rust")
}

/// Find a struct by name anywhere in the file, including inside `mod` blocks.
fn find_struct(file: &syn::File, name: &str) -> syn::ItemStruct {
    fn walk(items: &[syn::Item], name: &str) -> Option<syn::ItemStruct> {
        for item in items {
            match item {
                syn::Item::Struct(s) if s.ident == name => return Some(s.clone()),
                syn::Item::Mod(m) => {
                    if let Some((_, inner)) = &m.content {
                        if let Some(found) = walk(inner, name) {
                            return Some(found);
                        }
                    }
                }
                _ => {}
            }
        }
        None
    }
    walk(&file.items, name).unwrap_or_else(|| panic!("no struct named {name} in the program"))
}

/// Render a type the way it is written in source, with spacing normalised.
fn type_string(ty: &syn::Type) -> String {
    ty.to_token_stream().to_string().replace(' ', "")
}

/// The attribute list on a named field, rendered to a normalised string.
fn field_attrs(field: &syn::Field) -> String {
    field
        .attrs
        .iter()
        .map(|a| a.to_token_stream().to_string())
        .collect::<Vec<_>>()
        .join(" ")
        .replace(' ', "")
}

fn named_fields(item: &syn::ItemStruct) -> Vec<syn::Field> {
    match &item.fields {
        syn::Fields::Named(named) => named.named.iter().cloned().collect(),
        _ => panic!("{} does not have named fields", item.ident),
    }
}

#[test]
fn the_program_source_is_parseable_rust() {
    // If this fails, every other assertion in the file is meaningless, so it is
    // asserted separately rather than left implicit in a helper.
    let file = parsed();
    assert!(
        !file.items.is_empty(),
        "the program source parsed to zero items"
    );
}

#[test]
fn the_record_struct_matches_the_layout_table_exactly() {
    use evidence_registry_spec::layout;

    let record = find_struct(&parsed(), "RecordV1");
    let fields = named_fields(&record);

    let actual: Vec<(String, String)> = fields
        .iter()
        .map(|f| (f.ident.as_ref().unwrap().to_string(), type_string(&f.ty)))
        .collect();

    let expected: Vec<(String, String)> = layout::FIELDS
        .iter()
        .map(|f| (f.name.to_string(), f.ty.replace(' ', "")))
        .collect();

    // Order matters as much as membership: borsh serialises in declaration
    // order, so a reordering silently changes every offset a verifier filters on.
    assert_eq!(
        actual, expected,
        "RecordV1's fields no longer match layout::FIELDS. Borsh offsets are \
         declaration order, so this is a wire-format change: update the table and \
         the SEED_PREFIX together, as a new account version."
    );
}

#[test]
fn the_record_struct_carries_the_anchor_account_attribute() {
    let record = find_struct(&parsed(), "RecordV1");
    let attrs = record
        .attrs
        .iter()
        .map(|a| a.to_token_stream().to_string().replace(' ', ""))
        .collect::<Vec<_>>()
        .join(" ");
    assert!(
        attrs.contains("#[account]"),
        "RecordV1 must carry #[account]; without it there is no 8-byte \
         discriminator and every layout offset in the table is wrong. Found: {attrs}"
    );
}

#[test]
fn the_declared_space_matches_the_layout_total() {
    use evidence_registry_spec::layout;

    let accounts = find_struct(&parsed(), "AnchorEvidence");
    let record_field = named_fields(&accounts)
        .into_iter()
        .find(|f| f.ident.as_ref().unwrap() == "record")
        .expect("AnchorEvidence has no `record` field");

    let attrs = field_attrs(&record_field);
    let expected = format!("space=8+{}", layout::FIELDS_LEN);
    assert!(
        attrs.contains(&expected),
        "the `record` account must declare `{expected}` (total {}), otherwise the \
         program asks the System program for the wrong rent-exempt size. Found: {attrs}",
        layout::ACCOUNT_LEN
    );
}

#[test]
fn the_seeds_match_the_spec_in_order() {
    let accounts = find_struct(&parsed(), "AnchorEvidence");
    let record_field = named_fields(&accounts)
        .into_iter()
        .find(|f| f.ident.as_ref().unwrap() == "record")
        .expect("AnchorEvidence has no `record` field");
    let attrs = field_attrs(&record_field);

    // The seed list, element for element. The commitment must be last so the
    // address binds every anchored field; the authority must be present so a
    // root is not content-addressed and therefore front-runnable.
    let expected = "seeds=[seeds::SEED_PREFIX,authority.key().as_ref(),commitment_arg.as_ref()]";
    assert!(
        attrs.contains(expected),
        "the PDA seeds no longer match the spec. Expected `{expected}`. Found: {attrs}"
    );
}

#[test]
fn the_bump_takes_no_argument() {
    // A caller-supplied bump lets one commitment mint several distinct accounts,
    // destroying the one-anchor-per-commitment property. `non-canonical-bump` is
    // in ARES's own vulnerability catalog.
    let accounts = find_struct(&parsed(), "AnchorEvidence");
    let record_field = named_fields(&accounts)
        .into_iter()
        .find(|f| f.ident.as_ref().unwrap() == "record")
        .expect("AnchorEvidence has no `record` field");
    let attrs = field_attrs(&record_field);

    assert!(
        attrs.contains("bump"),
        "the record account must derive a bump"
    );
    assert!(
        !attrs.contains("bump="),
        "`bump = <expr>` accepts a caller-supplied bump. Use a bare `bump` so \
         Anchor derives the canonical one. Found: {attrs}"
    );
}

#[test]
fn the_authority_is_a_mutable_signer() {
    let accounts = find_struct(&parsed(), "AnchorEvidence");
    let authority = named_fields(&accounts)
        .into_iter()
        .find(|f| f.ident.as_ref().unwrap() == "authority")
        .expect("AnchorEvidence has no `authority` field");

    // Signer is what makes the claim attributable at all; `mut` is required
    // because the authority is also the payer.
    assert_eq!(type_string(&authority.ty), "Signer<'info>");
    assert!(
        field_attrs(&authority).contains("mut"),
        "the authority pays rent, so it must be #[account(mut)]"
    );
}

#[test]
fn init_if_needed_appears_nowhere() {
    // The overwrite footgun: it would silently accept a second anchor at an
    // existing address instead of failing, which is exactly the replay the plain
    // `init` prevents.
    assert!(
        !PROGRAM_SRC.contains("init_if_needed"),
        "init_if_needed must never appear: it turns the re-anchor rejection into \
         an overwrite"
    );
}

#[test]
fn there_is_no_update_close_or_set_authority_instruction() {
    // An anchor that can change is not an anchor, and a close makes it deniable.
    for forbidden in ["fn update", "fn close", "fn set_authority", "fn set_root"] {
        assert!(
            !PROGRAM_SRC.contains(forbidden),
            "found `{forbidden}` -- the record is immutable by design. Mutability \
             would mean a reader at T2 cannot know what the record said at T1."
        );
    }
}

#[test]
fn every_documented_reject_is_declared() {
    // Declared, NOT proven enforced -- see the module docs. Each of these is a
    // `require!` whose absence would let a permanently-recorded bad value land.
    for (needle, why) in [
        (
            "EvidenceError::ZeroRoot",
            "an all-zero root would be recorded forever",
        ),
        (
            "EvidenceError::ZeroReportDigest",
            "an all-zero report digest means the client emitted nothing",
        ),
        (
            "EvidenceError::ZeroTargetBinding",
            "an all-zero target binding anchors a root against no target",
        ),
        (
            "EvidenceError::CommitmentMismatch",
            "without it the seeds no longer bind the anchored data to the address",
        ),
        (
            "EvidenceError::UnexpectedAccounts",
            "remaining-accounts validation",
        ),
    ] {
        assert!(
            PROGRAM_SRC.contains(needle),
            "missing reject `{needle}`: {why}"
        );
    }
    // And the require! calls themselves, not just the error variants.
    assert!(
        PROGRAM_SRC.matches("require!").count() >= 5,
        "expected at least five require! calls, found {}",
        PROGRAM_SRC.matches("require!").count()
    );
}

#[test]
fn the_clock_is_read_via_the_syscall_not_a_sysvar_account() {
    // Passing Clock as an account is `sysvar-spoofing` in ARES's own catalog, and
    // the timestamp is the one input the submitter must not control.
    assert!(
        PROGRAM_SRC.contains("Clock::get()"),
        "the program must read the clock via Clock::get()"
    );
    let accounts = find_struct(&parsed(), "AnchorEvidence");
    for field in named_fields(&accounts) {
        let ty = type_string(&field.ty);
        assert!(
            !ty.contains("Sysvar<") && !ty.contains("Clock"),
            "the accounts struct must not take a sysvar account; found {ty}"
        );
    }
}

#[test]
fn the_accounts_struct_takes_exactly_three_accounts() {
    // Any extra account is surface a reviewer has to reason about, and the
    // payload builder enumerates these positionally.
    let accounts = find_struct(&parsed(), "AnchorEvidence");
    let names: Vec<String> = named_fields(&accounts)
        .iter()
        .map(|f| f.ident.as_ref().unwrap().to_string())
        .collect();
    assert_eq!(names, vec!["record", "authority", "system_program"]);
}

#[test]
fn the_instruction_name_matches_the_discriminator_preimage() {
    use evidence_registry_spec::discriminator::INSTRUCTION_PREIMAGE;

    let name = INSTRUCTION_PREIMAGE
        .strip_prefix("global:")
        .expect("the preimage must start with `global:`");
    assert!(
        PROGRAM_SRC.contains(&format!("pub fn {name}(")),
        "the discriminator preimage names `{name}`, but no `pub fn {name}(` exists. \
         A mismatch here means every client would send an instruction the program \
         cannot route."
    );
}

#[test]
fn the_program_id_is_still_the_documented_placeholder() {
    // A tripwire, deliberately asserting the incomplete state.
    //
    // The program has never been deployed, so there is no real id to declare. When
    // an operator generates the program keypair and deploys, THIS TEST MUST BE
    // UPDATED as part of that task -- which is the point. It makes "we never
    // deployed" a fact CI restates on every run rather than a caveat in a README
    // that drifts.
    assert!(
        PROGRAM_SRC.contains(PLACEHOLDER_PROGRAM_ID),
        "declare_id! no longer holds the placeholder. If the program has been \
         deployed, update this test, the README's never-deployed disclaimer, and \
         the payload builder's placeholder rejection together."
    );
}

#[test]
fn the_program_source_documents_that_it_was_never_compiled() {
    // The single biggest dishonesty risk in this task is a green badge over an
    // uncompiled program. The disclaimer is load-bearing, so it is pinned.
    assert!(
        PROGRAM_SRC.contains("NEVER COMPILED, NEVER DEPLOYED"),
        "the program's own header must state that it has never been built or \
         deployed; the host tests here check a specification, not a binary"
    );
}
