-- ARES RBAC: roles, permissions, auth hook, and RLS for knowledge tables.
-- Adapted from Supabase custom-claims RBAC guide for documents/chunks.
--
-- After applying: enable the auth hook in Supabase Dashboard →
-- Authentication → Hooks → Custom Access Token → public.custom_access_token_hook
--
-- Server-side ARES ingest/recall uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.

-- ---------------------------------------------------------------------------
-- Types
-- ---------------------------------------------------------------------------
create type public.app_permission as enum (
  'knowledge.read',
  'knowledge.write',
  'knowledge.delete'
);

create type public.app_role as enum (
  'admin',
  'auditor',
  'viewer'
);

-- ---------------------------------------------------------------------------
-- Role tables
-- ---------------------------------------------------------------------------
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  role      app_role not null,
  unique (user_id, role)
);

comment on table public.user_roles is 'Application roles for each Supabase Auth user.';

create table public.role_permissions (
  id         bigint generated by default as identity primary key,
  role       app_role not null,
  permission app_permission not null,
  unique (role, permission)
);

comment on table public.role_permissions is 'Permissions granted to each application role.';

insert into public.role_permissions (role, permission)
values
  ('admin',   'knowledge.read'),
  ('admin',   'knowledge.write'),
  ('admin',   'knowledge.delete'),
  ('auditor', 'knowledge.read'),
  ('auditor', 'knowledge.write'),
  ('viewer',  'knowledge.read');

-- ---------------------------------------------------------------------------
-- authorize() — read user_role claim from JWT, check role_permissions
-- ---------------------------------------------------------------------------
create or replace function public.authorize(requested_permission app_permission)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  bind_permissions int;
  user_role public.app_role;
begin
  select (auth.jwt() ->> 'user_role')::public.app_role into user_role;

  select count(*)
  into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = user_role;

  return bind_permissions > 0;
end;
$$;

-- ---------------------------------------------------------------------------
-- Custom Access Token Auth Hook — inject user_role into JWT
-- ---------------------------------------------------------------------------
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  select role into user_role
  from public.user_roles
  where user_id = (event->>'user_id')::uuid;

  claims := event->'claims';

  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', 'null');
  end if;

  event := jsonb_set(event, '{claims}', claims);
  return event;
end;
$$;

grant usage on schema public to supabase_auth_admin;

grant execute on function public.custom_access_token_hook to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;

grant all on table public.user_roles to supabase_auth_admin;
revoke all on table public.user_roles from authenticated, anon, public;

create policy "Allow auth admin to read user roles"
  on public.user_roles
  as permissive
  for select
  to supabase_auth_admin
  using (true);

-- ---------------------------------------------------------------------------
-- RLS on knowledge tables
-- ---------------------------------------------------------------------------
alter table public.documents enable row level security;
alter table public.chunks enable row level security;

create policy "Knowledge read access"
  on public.documents
  for select
  to authenticated
  using ((select public.authorize('knowledge.read')));

create policy "Knowledge write access"
  on public.documents
  for insert
  to authenticated
  with check ((select public.authorize('knowledge.write')));

create policy "Knowledge update access"
  on public.documents
  for update
  to authenticated
  using ((select public.authorize('knowledge.write')))
  with check ((select public.authorize('knowledge.write')));

create policy "Knowledge delete access"
  on public.documents
  for delete
  to authenticated
  using ((select public.authorize('knowledge.delete')));

create policy "Knowledge read access"
  on public.chunks
  for select
  to authenticated
  using ((select public.authorize('knowledge.read')));

create policy "Knowledge write access"
  on public.chunks
  for insert
  to authenticated
  with check ((select public.authorize('knowledge.write')));

create policy "Knowledge update access"
  on public.chunks
  for update
  to authenticated
  using ((select public.authorize('knowledge.write')))
  with check ((select public.authorize('knowledge.write')));

create policy "Knowledge delete access"
  on public.chunks
  for delete
  to authenticated
  using ((select public.authorize('knowledge.delete')));
