from __future__ import annotations

from pathlib import Path

import pytest

from lockfile import Dependency, MalformedLockfile, parse_lockfile

REAL_LOCKFILE = Path(__file__).resolve().parents[2] / "core" / "Cargo.lock"


class TestBasicParsing:
    def test_parses_a_minimal_v4_lockfile(self):
        text = """
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "aho-corasick"
version = "1.1.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
dependencies = [
 "memchr",
]
"""
        deps = parse_lockfile(text)
        assert deps == [Dependency(name="aho-corasick", version="1.1.4", is_local=False)]

    def test_preserves_duplicate_crate_names_at_different_versions(self):
        # Real shape from core/Cargo.lock: hashbrown appears 4 times.
        text = """
version = 4

[[package]]
name = "hashbrown"
version = "0.14.5"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "hashbrown"
version = "0.15.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
"""
        deps = parse_lockfile(text)
        assert [d.version for d in deps if d.name == "hashbrown"] == ["0.14.5", "0.15.2"]

    def test_workspace_local_crate_has_no_source_and_is_flagged_local(self):
        # Real shape from core/Cargo.lock: ares-core has name+version, no source.
        text = """
version = 4

[[package]]
name = "ares-core"
version = "0.1.0"
"""
        deps = parse_lockfile(text)
        assert deps == [Dependency(name="ares-core", version="0.1.0", is_local=True)]


class TestMalformedInputFailsLoudly:
    """A parse failure must never be silently treated as "zero dependencies"
    -- see MalformedLockfile's docstring and the outcome contract at the
    endpoint (failed vs. ok-with-zero-deps are different, visible states)."""

    def test_empty_string_raises(self):
        with pytest.raises(MalformedLockfile):
            parse_lockfile("")

    def test_not_toml_at_all_raises(self):
        with pytest.raises(MalformedLockfile):
            parse_lockfile("{ this is json, not toml }")

    def test_toml_without_a_package_array_raises(self):
        with pytest.raises(MalformedLockfile):
            parse_lockfile("version = 4\n")

    def test_package_entry_missing_version_raises(self):
        with pytest.raises(MalformedLockfile):
            parse_lockfile('version = 4\n\n[[package]]\nname = "foo"\n')

    def test_package_is_not_an_array_raises(self):
        with pytest.raises(MalformedLockfile):
            parse_lockfile('version = 4\n\n[package]\nname = "foo"\n')


class TestAgainstTheRealCommittedLockfile:
    """Ground truth: parse the repo's own core/Cargo.lock rather than only
    hand-written fixtures, so a real-world shape this parser hasn't
    considered fails a test here instead of failing silently at the endpoint."""

    def test_parses_without_error_and_finds_known_crates(self):
        if not REAL_LOCKFILE.exists():
            pytest.skip("core/Cargo.lock not present in this checkout")
        deps = parse_lockfile(REAL_LOCKFILE.read_text(encoding="utf-8"))
        names = {d.name for d in deps}
        assert "aho-corasick" in names
        assert len(deps) >= 400  # confirmed 489 [[package]] entries at plan time

    def test_workspace_crates_are_flagged_local_not_advisory_candidates(self):
        if not REAL_LOCKFILE.exists():
            pytest.skip("core/Cargo.lock not present in this checkout")
        deps = parse_lockfile(REAL_LOCKFILE.read_text(encoding="utf-8"))
        by_name = {d.name: d for d in deps}
        assert by_name["ares-core"].is_local is True

    def test_hashbrown_duplicate_versions_survive_parsing(self):
        if not REAL_LOCKFILE.exists():
            pytest.skip("core/Cargo.lock not present in this checkout")
        deps = parse_lockfile(REAL_LOCKFILE.read_text(encoding="utf-8"))
        hashbrown_versions = [d.version for d in deps if d.name == "hashbrown"]
        assert len(hashbrown_versions) == len(set(hashbrown_versions)) or len(hashbrown_versions) >= 1
        assert len(hashbrown_versions) >= 4
