//! `evidence_registry` -- anchors an ARES evidence Merkle root on Solana.
//!
//! # NEVER COMPILED, NEVER DEPLOYED
//!
//! This source has not been built to SBF and no cluster carries this program.
//! There is no `solana` CLI, no `anchor` CLI and no `cargo build-sbf` in this
//! repository's CI or on the machine it was written on. What *is* mechanically
//! checked is the specification it implements: every constant, offset and
//! preimage lives in `evidence-registry-spec`, which compiles and tests on the
//! host target, and `tests/program_source_conformance.rs` parses this file with
//! `syn` and asserts it matches that table.
//!
//! So the honest claim is: **the constraints below are asserted to be declared,
//! not proven to be enforced.** Proving enforcement needs `anchor test` against a
//! localnet, which is a deferred task. See `../../../README.md`.
//!
//! # What this program does
//!
//! Stores a 32-byte root. It does **not** verify Merkle proofs -- it cannot see
//! the leaves, and no on-chain party benefits from re-deriving a root it has no
//! inputs for. Proof verification is a client operation. An anchor's whole job is
//! to timestamp 32 bytes against a clock the submitter does not control.
//!
//! # What an anchor proves, and does not
//!
//! Proves: the holder of `authority` published this `(root, leaf_count,
//! report_sha256, target_binding)` tuple in a transaction included at some slot.
//! That is an *upper bound on when the root was known*, and nothing more.
//!
//! Does not prove the audit happened, was competent, or was complete -- the chain
//! sees 32 bytes and cannot tell a real audit from `sha256(random)`. Does not
//! prove findings were not withheld: you can prove a finding *was* in the
//! committed set, never that one was not held back. Does not prove `authority`
//! is who they claim. Does not prove the root concerns the claimed target, since
//! `target_binding` is self-asserted and anyone can anchor anything for ~0.002
//! SOL. Does not give a *lower* bound on time.
//!
//! Every immutability claim here is also conditional on the upgrade authority
//! being renounced. An upgrade authority can deploy a version with an
//! arbitrary-write instruction and rewrite any record, so
//! `set-upgrade-authority --final` must happen before the first real anchor --
//! and renouncing later does not retroactively secure earlier anchors, because a
//! different binary may have been deployed in the interim. ARES's own detector
//! flags `upgrade-authority-risk`; an ARES-authored program that stays upgradeable
//! fails its own audit.

use anchor_lang::prelude::*;
use evidence_registry_spec::{commitment, layout, merkle, seeds};

// Placeholder. Replaced with the real program id once an operator generates the
// program keypair -- that keypair is a private key, so it is generated by a human
// and never by CI. The conformance test fails while this placeholder is present,
// and the payload builder refuses to emit a transaction for it.
declare_id!("Evid1111111111111111111111111111111111111111");

#[program]
pub mod evidence_registry {
    use super::*;

    /// Record one evidence commitment. The only instruction.
    ///
    /// # Rejects
    ///
    /// - an already-anchored commitment, via `init` -- `create_account` fails on
    ///   an existing account and Anchor additionally requires a zeroed
    ///   discriminator, so re-initialisation is structurally unreachable
    /// - an unsigned authority, via `Signer`
    /// - a caller-supplied bump, by taking none (a chosen bump would let one
    ///   commitment mint several accounts)
    /// - a `commitment` argument that does not match the one recomputed here
    /// - an all-zero `root`, `report_sha256` or `target_binding`: a client
    ///   emitting zeros is the likeliest real bug, and it would be recorded
    ///   forever
    /// - any extra accounts
    pub fn anchor_evidence(
        ctx: Context<AnchorEvidence>,
        leaf_count: u32,
        root: [u8; 32],
        report_sha256: [u8; 32],
        target_binding: [u8; 32],
        commitment_arg: [u8; 32],
    ) -> Result<()> {
        require!(root != [0u8; 32], EvidenceError::ZeroRoot);
        require!(report_sha256 != [0u8; 32], EvidenceError::ZeroReportDigest);
        require!(target_binding != [0u8; 32], EvidenceError::ZeroTargetBinding);
        require!(
            ctx.remaining_accounts.is_empty(),
            EvidenceError::UnexpectedAccounts
        );

        // Recompute the commitment from the arguments and require it to match the
        // one used in the seeds. Combined with the runtime's own PDA check, this
        // makes it impossible to land a record whose data disagrees with its
        // address -- which is what lets an operator trust the PDA in a payload
        // they reviewed rather than treating it as a separate input.
        let expected = anchor_lang::solana_program::hash::hash(&commitment::preimage(
            leaf_count,
            &root,
            &report_sha256,
            &target_binding,
        ))
        .to_bytes();
        require!(
            expected == commitment_arg,
            EvidenceError::CommitmentMismatch
        );

        // Clock::get() is the syscall, NOT a sysvar account. Passing the sysvar
        // as an account would be `sysvar-spoofing` in ARES's own catalog.
        let clock = Clock::get()?;

        let record = &mut ctx.accounts.record;
        record.authority = ctx.accounts.authority.key();
        record.root = root;
        record.report_sha256 = report_sha256;
        record.target_binding = target_binding;
        record.leaf_count = leaf_count;
        record.slot = clock.slot;
        record.unix_timestamp = clock.unix_timestamp;
        record.bump = ctx.bumps.record;
        Ok(())
    }
}

/// Accounts for [`anchor_evidence`].
///
/// `payer == authority` is deliberate, not laziness: a distinct payer means two
/// signers, which makes "who claimed this" ambiguous and makes the transaction
/// materially harder for an operator to sign with one wallet. One signer, one
/// key, one claim.
#[derive(Accounts)]
#[instruction(
    leaf_count: u32,
    root: [u8; 32],
    report_sha256: [u8; 32],
    target_binding: [u8; 32],
    commitment_arg: [u8; 32]
)]
pub struct AnchorEvidence<'info> {
    #[account(
        init,
        payer = authority,
        space = 8 + 149,
        seeds = [seeds::SEED_PREFIX, authority.key().as_ref(), commitment_arg.as_ref()],
        bump
    )]
    pub record: Account<'info, RecordV1>,

    #[account(mut)]
    pub authority: Signer<'info>,

    pub system_program: Program<'info, System>,
}

/// One immutable evidence anchor.
///
/// Field order matches `layout::FIELDS` and is part of the contract: a verifier
/// filters with `getProgramAccounts` on `dataSize` plus memcmp at `authority`
/// (offset 8) and `target_binding` (offset 104).
///
/// There is no `update`, no `close` and no `set_authority`. An anchor that can
/// change is not an anchor, and a `close` would make it deniable -- evidence you
/// can delete after the fact is not evidence. The cost is that the rent is spent
/// permanently, which is the correct trade and is stated rather than hidden.
#[account]
pub struct RecordV1 {
    /// Who asserted this root.
    pub authority: Pubkey,
    /// The RFC 6962 Merkle root over the canonical finding leaves.
    pub root: [u8; 32],
    /// SHA-256 of the exact report bytes the bundle was built from.
    pub report_sha256: [u8; 32],
    /// Binds target name, commit, engine version, claimed program id, report kind.
    pub target_binding: [u8; 32],
    /// Number of leaves. Without it, an inclusion proof is shape-malleable.
    pub leaf_count: u32,
    /// Slot from `Clock::get()`. The authoritative ordering primitive.
    pub slot: u64,
    /// Unix timestamp from `Clock::get()`. A stake-weighted median of validator
    /// vote timestamps, so it can drift by minutes -- a convenience, not the claim.
    pub unix_timestamp: i64,
    /// Cached canonical bump.
    pub bump: u8,
}

/// Failures [`anchor_evidence`] rejects.
#[error_code]
pub enum EvidenceError {
    /// The root was all zeros.
    #[msg("root must not be all zeros")]
    ZeroRoot,
    /// The report digest was all zeros.
    #[msg("report_sha256 must not be all zeros")]
    ZeroReportDigest,
    /// The target binding was all zeros.
    #[msg("target_binding must not be all zeros")]
    ZeroTargetBinding,
    /// The supplied commitment did not match the recomputed one.
    #[msg("commitment does not match the recomputed preimage")]
    CommitmentMismatch,
    /// Extra accounts were passed.
    #[msg("no additional accounts are expected")]
    UnexpectedAccounts,
}

// A compile-time cross-check against the spec crate, so `space` above and the
// layout table cannot drift even before the syn conformance test runs.
const _: () = assert!(layout::ACCOUNT_LEN == 157);
const _: () = assert!(layout::FIELDS_LEN == 149);
const _: () = assert!(merkle::HASH_SIZE == 32);
const _: () = assert!(seeds::SEED_COUNT == 3);
